### ISSUE TITLE
Error while loading files with Mincraft 1.20.12

### ISSUE THREAD

**Issue by m59deathman** [tryashtar/nbt-studio#54]
If i try to load the level.dat i get the following error:

4 files failed to load:

levelname.txt
world_behavior_packs.json
world_icon.jpeg
world_resource_packs.json

File did not begin with a '{'
Could not auto-detect compression format.
Invalid region file, thinks there's a 466944-long chunk at position 384188416 but file is only 12 long
Attempted to read past the end of the stream.
Falscher Parameter. : 'C:\Users\Andre\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\sYSkZE3+IwA=\world_behavior_packs.json'
Falscher Parameter. : 'C:\Users\Andre\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\sYSkZE3+IwA=\world_icon.jpeg'
Falscher Parameter. : 'C:\Users\Andre\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\sYSkZE3+IwA=\world_resource_packs.json'

Load as SNBT:
System.FormatException: File did not begin with a '{'
   at NbtStudio.NbtFile.CreateFromSnbt(String path)
   at NbtStudio.NbtFile.<>c__DisplayClass32_0.<TryCreateFromSnbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as NBT (compression: AutoDetect, big endian: True, bedrock header: False):
System.IO.InvalidDataException: Could not auto-detect compression format.
   at fNbt.NbtFile.DetectCompression(Stream stream)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression)
   at NbtStudio.NbtFile.CreateFromNbt(String path, NbtCompression compression, Boolean big_endian, Boolean bedrock_header)
   at NbtStudio.NbtFile.<>c__DisplayClass34_0.<TryCreateFromNbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as NBT (compression: AutoDetect, big endian: False, bedrock header: False):
System.IO.InvalidDataException: Could not auto-detect compression format.
   at fNbt.NbtFile.DetectCompression(Stream stream)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression)
   at NbtStudio.NbtFile.CreateFromNbt(String path, NbtCompression compression, Boolean big_endian, Boolean bedrock_header)
   at NbtStudio.NbtFile.<>c__DisplayClass34_0.<TryCreateFromNbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as NBT (compression: AutoDetect, big endian: False, bedrock header: True):
System.IO.InvalidDataException: Could not auto-detect compression format.
   at fNbt.NbtFile.DetectCompression(Stream stream)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression)
   at NbtStudio.NbtFile.CreateFromNbt(String path, NbtCompression compression, Boolean big_endian, Boolean bedrock_header)
   at NbtStudio.NbtFile.<>c__DisplayClass34_0.<TryCreateFromNbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as region file:
System.FormatException: Invalid region file, thinks there's a 466944-long chunk at position 384188416 but file is only 12 long
   at NbtStudio.RegionFile.Load()
   at NbtStudio.RegionFile..ctor(String path)
   at NbtStudio.RegionFile.<>c__DisplayClass35_0.<TryCreate>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as SNBT:
System.FormatException: File did not begin with a '{'
   at NbtStudio.NbtFile.CreateFromSnbt(String path)
   at NbtStudio.NbtFile.<>c__DisplayClass32_0.<TryCreateFromSnbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as NBT (compression: AutoDetect, big endian: True, bedrock header: False):
System.IO.InvalidDataException: Could not auto-detect compression format.
   at fNbt.NbtFile.DetectCompression(Stream stream)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression)
   at NbtStudio.NbtFile.CreateFromNbt(String path, NbtCompression compression, Boolean big_endian, Boolean bedrock_header)
   at NbtStudio.NbtFile.<>c__DisplayClass34_0.<TryCreateFromNbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as NBT (compression: AutoDetect, big endian: False, bedrock header: False):
System.IO.InvalidDataException: Could not auto-detect compression format.
   at fNbt.NbtFile.DetectCompression(Stream stream)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression)
   at NbtStudio.NbtFile.CreateFromNbt(String path, NbtCompression compression, Boolean big_endian, Boolean bedrock_header)
   at NbtStudio.NbtFile.<>c__DisplayClass34_0.<TryCreateFromNbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as NBT (compression: AutoDetect, big endian: False, bedrock header: True):
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at fNbt.NbtFile.DetectCompression(Stream stream)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression)
   at NbtStudio.NbtFile.CreateFromNbt(String path, NbtCompression compression, Boolean big_endian, Boolean bedrock_header)
   at NbtStudio.NbtFile.<>c__DisplayClass34_0.<TryCreateFromNbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as region file:
System.IO.IOException: Falscher Parameter. : 'C:\Users\Andre\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\sYSkZE3+IwA=\world_behavior_packs.json'
   at System.IO.Strategies.FileStreamHelpers.ThrowInvalidArgument(SafeFileHandle handle)
   at System.IO.Strategies.OSFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Strategies.BufferedFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at NbtStudio.Chunk.Load()
   at NbtStudio.RegionFile.Load()
   at NbtStudio.RegionFile..ctor(String path)
   at NbtStudio.RegionFile.<>c__DisplayClass35_0.<TryCreate>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as SNBT:
System.FormatException: File did not begin with a '{'
   at NbtStudio.NbtFile.CreateFromSnbt(String path)
   at NbtStudio.NbtFile.<>c__DisplayClass32_0.<TryCreateFromSnbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as NBT (compression: AutoDetect, big endian: True, bedrock header: False):
System.IO.InvalidDataException: Could not auto-detect compression format.
   at fNbt.NbtFile.DetectCompression(Stream stream)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression)
   at NbtStudio.NbtFile.CreateFromNbt(String path, NbtCompression compression, Boolean big_endian, Boolean bedrock_header)
   at NbtStudio.NbtFile.<>c__DisplayClass34_0.<TryCreateFromNbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as NBT (compression: AutoDetect, big endian: False, bedrock header: False):
System.IO.InvalidDataException: Could not auto-detect compression format.
   at fNbt.NbtFile.DetectCompression(Stream stream)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression)
   at NbtStudio.NbtFile.CreateFromNbt(String path, NbtCompression compression, Boolean big_endian, Boolean bedrock_header)
   at NbtStudio.NbtFile.<>c__DisplayClass34_0.<TryCreateFromNbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as NBT (compression: AutoDetect, big endian: False, bedrock header: True):
System.IO.InvalidDataException: Could not auto-detect compression format.
   at fNbt.NbtFile.DetectCompression(Stream stream)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression)
   at NbtStudio.NbtFile.CreateFromNbt(String path, NbtCompression compression, Boolean big_endian, Boolean bedrock_header)
   at NbtStudio.NbtFile.<>c__DisplayClass34_0.<TryCreateFromNbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as region file:
System.IO.IOException: Falscher Parameter. : 'C:\Users\Andre\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\sYSkZE3+IwA=\world_icon.jpeg'
   at System.IO.Strategies.FileStreamHelpers.ThrowInvalidArgument(SafeFileHandle handle)
   at System.IO.Strategies.OSFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Strategies.BufferedFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at NbtStudio.Chunk.Load()
   at NbtStudio.RegionFile.Load()
   at NbtStudio.RegionFile..ctor(String path)
   at NbtStudio.RegionFile.<>c__DisplayClass35_0.<TryCreate>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as SNBT:
System.FormatException: File did not begin with a '{'
   at NbtStudio.NbtFile.CreateFromSnbt(String path)
   at NbtStudio.NbtFile.<>c__DisplayClass32_0.<TryCreateFromSnbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as NBT (compression: AutoDetect, big endian: True, bedrock header: False):
System.IO.InvalidDataException: Could not auto-detect compression format.
   at fNbt.NbtFile.DetectCompression(Stream stream)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression)
   at NbtStudio.NbtFile.CreateFromNbt(String path, NbtCompression compression, Boolean big_endian, Boolean bedrock_header)
   at NbtStudio.NbtFile.<>c__DisplayClass34_0.<TryCreateFromNbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as NBT (compression: AutoDetect, big endian: False, bedrock header: False):
System.IO.InvalidDataException: Could not auto-detect compression format.
   at fNbt.NbtFile.DetectCompression(Stream stream)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression)
   at NbtStudio.NbtFile.CreateFromNbt(String path, NbtCompression compression, Boolean big_endian, Boolean bedrock_header)
   at NbtStudio.NbtFile.<>c__DisplayClass34_0.<TryCreateFromNbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as NBT (compression: AutoDetect, big endian: False, bedrock header: True):
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at fNbt.NbtFile.DetectCompression(Stream stream)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression)
   at NbtStudio.NbtFile.CreateFromNbt(String path, NbtCompression compression, Boolean big_endian, Boolean bedrock_header)
   at NbtStudio.NbtFile.<>c__DisplayClass34_0.<TryCreateFromNbt>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

Load as region file:
System.IO.IOException: Falscher Parameter. : 'C:\Users\Andre\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\sYSkZE3+IwA=\world_resource_packs.json'
   at System.IO.Strategies.FileStreamHelpers.ThrowInvalidArgument(SafeFileHandle handle)
   at System.IO.Strategies.OSFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Strategies.BufferedFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at NbtStudio.Chunk.Load()
   at NbtStudio.RegionFile.Load()
   at NbtStudio.RegionFile..ctor(String path)
   at NbtStudio.RegionFile.<>c__DisplayClass35_0.<TryCreate>b__0()
   at TryashtarUtils.Utility.Failable`1..ctor(Func`1 operation, String description)

**Comment by 1coolmatt8083** [comment]
so what you can try is use the exact same file and update it to the same file date.
